name: AltManager
main: com.civclassic.altmanager.AltManager
version: ${project.version}
author: biggestnerd
<<<<<<< HEAD
depend: [CivModCore, NameLayer, BanStick]
softdepend: [ExilePearl, PrisonPearl]
=======
depend: [CivModCore, ExilePearl, BanStick]
>>>>>>> branch 'master' of https://github.com/civclassic/altmanager
commands:
  alts:
    description: Interact with the alt list
    usage: "Usage: /alts <player>"
    permission: altmanager.admin
  altstats:
    description: Check some stats
    usage: "Usage: /altstats"
    permission: altmanager.admin
  reloadexceptions:
    description: Reloads exceptions
    usage: "Usage: /reloadexceptions"
    permission: altmanager.admin
permissions:
  altmanager.admin:
    description: Allows usage of the altlist command
    default: op
